# Site Settings
title: friday.movie
email: odd.daboss@gmail.com
description: ดูหนัง-ฟังเพลงกัน วันศุกร์แล้วพวกเรา!
baseurl: "/friday.movie" # the subpath of your site, e.g. /blog
url: "https://sdeehub.github.io" # the base hostname & protocol for your site
google_analytics: "UA-91253622-9"

# User Settings
username: friday.movie
user_description: ความทรงจำของคืนวันศุกร์ ความทรงจำของคืนที่ได้ดูหนังสนุกๆ และนี่คือความทรงจำที่จะอยู่กับพวกเรา ... ไปอีกยาวนาน
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
# gems:
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
