# Site Settings
title: friday.sdee.co
email: youremail@xyz.com
description: ดูหนัง-ฟังเพลงกัน วันศุกร์แล้วพวกเรา!
baseurl: "/friday" # the subpath of your site, e.g. /blog
url: "http://sdeehub.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: friday
user_description: เย็นวันศุกร์ต้องทำอะไร? ถ้าไม่ใช่ดูหนังกับฟังเพลง - Yeah! วันศุกร์อีกแล้วพวกเรา
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
# gems:
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
